sudo: required
language: minimal

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/maps
    - IMAGE_TAG=${TRAVIS_BRANCH}

install:
  - docker build -t ${IMAGE_REPO}:${TRAVIS_COMMIT::12} -t ${IMAGE_REPO}:${TRAVIS_BRANCH} .
  - make setup

script:
  - make flake8
  - make isort
  - make license
  - make safety
  - make test-travis

before_deploy:
  - ./scripts/install_gcloud.sh
  - ./scripts/install_kubectl.sh
  - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      - secure: gbsKvkVOj0jG2cQMKF7TKA/LYY+0KqNcYnMoNqed2mNEvylKTjVBHJNCimK7jGPbmTTggMIjcMKtHg0eorRKjbJzrppV3DmVWovb9uoTU2NhXludRg/C8bjlVSf/RGde3cZCSxN5AkDZ6j20xFEKH2LbmGtISTitoqbmiChY6sK9/FULJqSe8GxehLjWh0nDXXBaUz4L4zTmUymivmQRQdGMC19NQ/OfX7Kv7LXk4utHEKC2r3d9hcCEBfNdxkaPq25eD0u+77VyWhzeQw7fAyBI4e2JkPfYDHakS4kZcG4iQZ/7bOSqAfSZhrqbxUUtYvfaFgDdhQung6mRZrlBIjO2rBF3SbiV+tiV/FJSFAHMteQAX6I+dA4GVdz3qZkkWFhknqPRwz73DBRag9rWBpv5M1Z4nLKX4hDfRLmgiwR49wBwLIEOxgluuQyXbAySqFDoLfPF30l10OsHl7+/NrNaCkF9OkcCC2GAdKhMiZrLrC4p6pJgTbm1RlpIVnwGOSLPrSTQH8JdwGNC4ZH3oXZiuYHhW0v+xzBEL2ptB7ECRCgxyyYxvch7sYjXg8FInQDEzLnUMWgNCYt/IMTR6zGrOJudPpIigw2CwuKLAZ/+vN1bINfAkBj7MSrU8k8khk47cJ87+f8c4wlfpATV9WEC6VSd9CVKedncgNrT/zo=
    on_success: change
    on_failure: change
    on_pull_requests: false
