os: linux
language: shell

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
- docker

env:
  global:
  - IMAGE=gcr.io/dd-decaf-cfbf6/maps
  - BRANCH=${TRAVIS_BRANCH}
  - BUILD_COMMIT=${TRAVIS_COMMIT}
  - SHORT_COMMIT=${TRAVIS_COMMIT:0:7}
  - BUILD_DATE=$(date -u +%Y-%m-%d)
  - BUILD_TAG=${BRANCH}_${BUILD_DATE}_${SHORT_COMMIT}
  - POSTGRES_PASS=secret

before_install:
- make setup

install:
- make build
- make build-travis
- make post-build
- make start

script:
- make style
- make safety
# Run the tests and report coverage (see https://docs.codecov.io/docs/testing-with-docker).
- docker-compose exec -e ENVIRONMENT=testing web pytest --cov=map_storage --cov-report=term --cov-report=xml
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- ./scripts/install_gcloud.sh
- ./scripts/install_kubectl.sh
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then make push; fi

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      - secure: "MBzAae9VJHJdGeEkXglgM0VVi3/dClw+aJDYU8hB6/GzVZYF4dayHWyWHoSePnEf37akWP21Y8iGH3swlGioN4+GBMMJOmu9VtF6JkYLyC4bL5B4E8wTBFFLH3n9wazzVN8jwpBDlOkKmpWH2+h3TxfhISVWU8tro5+DBKp05Di5thoPdQZSJgKZvskG/yOWHJKWleqVSukxnBjWpyWoqRrWOMlQpxJgul/ibuzdWcooh9GVfoSkK+C3HqXJjyUcHpP/SvP/jTYDWAjobeFknwLsKKv9RXBmbN8IduiKP1G/SjWpqv2DH/z9xJ7UiKutJI79qJda+MKe512k0HfOjb560zrAc0oPRMYBMrJaYiCQCkcxRt8/QwaugXc5XoMB7Aqxtelb0kPv28Oall8BAf2MxZC18F+Ic6Tckx8iDU32K/l+bi2KMU157Key1FiL2cqrAoCFwYaEVa/70a1BbsMW8ckWdyB5FJZYnfz8fLPiMu3/n79+kjeMqAYQ7oEjSzFwgzXleWh0m1863Vd/xqQfq+WqOw/eB9AfDSMoJSIlx4ZqHGJS801PDLEykDWZ9Th/5iSkt7RCSkozNOOs09KMgjlZ7crXnmfh7N1J5lK/+V1zOWMUtWZX1LgnJzL4Y1oDtkgUTywCVX+BZF1JQGKbNJxW9XJ/3IJa+aClpm8="
    on_success: change
    on_failure: change
    on_pull_requests: false
