version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_TAG=${BASE_TAG}
        - BUILD_COMMIT=${BUILD_COMMIT:-unknown}
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-unknown}
    image: gcr.io/dd-decaf-cfbf6/maps:${IMAGE_TAG:-latest}
    networks:
      default:
      DD-DeCaF:
        aliases:
          - map-storage
    depends_on:
      - postgres
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ".:/app"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - FLASK_APP=src/map_storage/wsgi.py
      - SCRIPT_NAME=${SCRIPT_NAME}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:4200}
      - SENTRY_DSN=${SENTRY_DSN}
      - IAM_API=${IAM_API:-https://api-staging.dd-decaf.eu/iam}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME:-postgres}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASS=${POSTGRES_PASS:-secret}

  postgres:
    image: postgres:9.6-alpine
    networks:
    - default
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASS:-secret}

# Additional services that the `web` service `depends_on` should usually only
# be on the default network and not exposed on the general network, i.e.,
# networks:
#   - default

networks:
  DD-DeCaF:
    external: true
