apiVersion: apps/v1
kind: Deployment
metadata:
  name: maps-production
spec:
  selector:
    matchLabels:
      app: maps
      env: production
  replicas: 1
  template:
    metadata:
      labels:
        app: maps
        env: production
    spec:
      containers:
      - name: web
        image: gcr.io/dd-decaf-cfbf6/maps:master
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: production
        - name: SCRIPT_NAME
          value: /filemapsservice
        - name: FLASK_APP
          value: src/filemapsservice/wsgi.py
        - name: ALLOWED_ORIGINS
          value: https://app.dd-decaf.eu,http://localhost:4200
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: maps-production
              key: SENTRY_DSN
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: maps-production
              key: SECRET_KEY
        command: ["gunicorn", "-c", "gunicorn.py", "filemapsservice.wsgi:app"]
        resources:
          requests:
            cpu: "10m"
          limits:
            cpu: "100m"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: maps-staging
spec:
  selector:
    matchLabels:
      app: maps
      env: staging
  replicas: 1
  template:
    metadata:
      labels:
        app: maps
        env: staging
    spec:
      containers:
      - name: web
        image: gcr.io/dd-decaf-cfbf6/maps:devel
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: staging
        - name: SCRIPT_NAME
          value: /filemapsservice
        - name: FLASK_APP
          value: src/filemapsservice/wsgi.py
        - name: ALLOWED_ORIGINS
          value: https://staging.dd-decaf.eu,http://localhost:4200
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: maps-staging
              key: SENTRY_DSN
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: maps-staging
              key: SECRET_KEY
        command: ["gunicorn", "-c", "gunicorn.py", "filemapsservice.wsgi:app"]
        resources:
          requests:
            cpu: "5m"
          limits:
            cpu: "100m"
