"""empty message

Revision ID: 550a8988a8b8
Revises: 755b5ad9a315
Create Date: 2018-11-15 15:26:20.221270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550a8988a8b8'
down_revision = '755b5ad9a315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_map_project_id'), 'map', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_map_project_id'), table_name='map')
    op.drop_column('map', 'project_id')
    # ### end Alembic commands ###
